name: Build and test
on:
  push:
    branches:
    - "**"
  pull_request:
jobs:
   gfortran:
      if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
      runs-on: "ubuntu-latest"
      defaults:
         run:
            shell: "bash -el {0}"
      steps:
        - name: add csh
          run: |
            sudo apt-get update
            sudo apt-get install csh
        - name: Clone
          uses: actions/checkout@v7
        - name: Clone FABM
          uses: actions/checkout@v7
          with:
            repository: fabm-model/fabm
            path: fabm
        - name: Setup miniconda
          uses: conda-incubator/setup-miniconda@v4
          with:
            auto-update-conda: true
            channels: conda-forge
            conda-remove-defaults: "true"
        - name: Install packages
          run: conda install gfortran netcdf-fortran cmake ninja mpi mpich
        - name: Compile FABM
          run: |
            cmake -S fabm -B fabm/build -G Ninja -DCMAKE_BUILD_TYPE=Release -DFABM_HOST=mom5 -DCMAKE_Fortran_COMPILER=gfortran 
            cmake --build fabm/build -t install
        - name: Patch compilation of mppnccombine for recent gfortran
          run: patch -p1 < .github/workflows/gfortran.patch
        - name: Compile MOM5 with FABM support
          run: |
            cd exp
            ./MOM_compile.csh --type MOM_SIS --platform conda
        - name: download and extract MOM_SIS_BLING input data
          run: |
            mkdir work
            cd work
            wget --no-verbose http://portal.sf.utas.edu.au/thredds/fileServer/momtest/test_data/MOM_SIS_BLING.input.tar.gz
            tar -xvf MOM_SIS_BLING.input.tar.gz
        - name: Patch setup to run with 1 core
          run: patch -p1 < .github/workflows/input_npes.patch
        - name: Run MOM5
          run: |
            cd exp
            ./MOM_run.csh --type MOM_SIS --experiment MOM_SIS_BLING --platform conda --npes 1
        - name: Run MOM5 with FABM
          run: |
            cd exp
            cat >> ../work/MOM_SIS_BLING/INPUT/field_table <<EOL
            "tracer_packages", "ocean_mod", "ocean_fabm"
              use=.true.
            /
            EOL
            cp ../fabm/testcases/fabm-gotm-npzd.yaml ../work/MOM_SIS_BLING/fabm.yaml
            ./MOM_run.csh --type MOM_SIS --experiment MOM_SIS_BLING --platform conda --npes 1
